[project]
name = "patcheval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arthur Chen", email = "arthur@collinear.ai" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
patcheval = "patcheval:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
